import delphivcl

comps = [
    delphivcl.Action,
    delphivcl.ActionList,
    delphivcl.ActivityIndicator,
    # delphivcl.# Application,
    delphivcl.BasicAction,
    delphivcl.Bevel,
    delphivcl.BitBtn,
    delphivcl.Bitmap,
    delphivcl.BoundLabel,
    delphivcl.Button,
    delphivcl.Canvas,
    delphivcl.CheckBox,
    delphivcl.Collection,
    delphivcl.ColorBox,
    delphivcl.ComboBox,
    delphivcl.Component,
    delphivcl.ContainedAction,
    delphivcl.ContainedActionList,
    delphivcl.Control,
    delphivcl.ControlBar,
    # delphivcl.# CreateComponent,
    delphivcl.CustomAction,
    delphivcl.CustomActionList,
    delphivcl.CustomActivityIndicator,
    delphivcl.CustomControl,
    delphivcl.CustomDrawGrid,
    delphivcl.CustomEdit,
    delphivcl.CustomForm,
    delphivcl.CustomGrid,
    delphivcl.CustomMemo,
    delphivcl.CustomStyleServices,
    delphivcl.CustomTabControl,
    delphivcl.CustomToggleSwitch,
    delphivcl.DateTimePicker,
    delphivcl.DelphiDefaultContainer,
    delphivcl.DelphiDefaultIterator,
    delphivcl.DelphiMethod,
    delphivcl.DrawGrid,
    delphivcl.Edit,
    delphivcl.FileOpenDialog,
    delphivcl.Form,
    delphivcl.Graphic,
    delphivcl.GroupBox,
    delphivcl.Header,
    delphivcl.Icon,
    delphivcl.Image,
    delphivcl.Label,
    delphivcl.LabeledEdit,
    delphivcl.ListBox,
    delphivcl.MainMenu,
    delphivcl.Memo,
    delphivcl.Menu,
    delphivcl.MenuItem,
    delphivcl.Metafile,
    delphivcl.Monitor,
    delphivcl.Notebook,
    delphivcl.Object,
    delphivcl.OpenDialog,
    delphivcl.Page,
    delphivcl.PageControl,
    delphivcl.PaintBox,
    delphivcl.Panel,
    delphivcl.PascalInterface,
    delphivcl.PascalRecord,
    delphivcl.Persistent,
    delphivcl.Picture,
    delphivcl.Point,
    delphivcl.PopupMenu,
    delphivcl.RadioButton,
    delphivcl.RadioGroup,
    delphivcl.Rect,
    # delphivcl.# Screen,
    delphivcl.ScrollBar,
    delphivcl.Shape,
    # delphivcl.# ShowMessage,
    delphivcl.Size,
    delphivcl.SpeedButton,
    delphivcl.SpinButton,
    delphivcl.SpinEdit,
    delphivcl.Splitter,
    delphivcl.StaticText,
    delphivcl.StringGrid,
    delphivcl.Strings,
    delphivcl.StyleInfo,
    delphivcl.StyleManager,
    # delphivcl.# StyleServices,
    delphivcl.TabControl,
    delphivcl.TabSheet,
    delphivcl.Timer,
    delphivcl.ToggleSwitch,
    delphivcl.ToolBar,
    delphivcl.ToolButton,
    delphivcl.TrackBar,
    delphivcl.VarParameter,
    delphivcl.WinControl
]


def main(self, *args, **kwargs):

    for key, value in kwargs.items():
        setattr(self, key, value)


def change_types():
    for c in comps:
        newc = type(c.__name__,
                    (c,),
                    {"__init__": main})

        setattr(delphivcl, c.__name__, newc)


change_types()
